### ISSUE TITLE
Waschdauer + Prozent nicht mehr da

### ISSUE THREAD

**Issue by Hini2001** [TA2k/ioBroker.smartthings#15]
Moin,

seit einigen Tagen werden leider die Datenpunkte unserer Waschmaschine unter STATUS - SWITCH nicht mehr aktualisiert. Nach dem löschen aller Ordner und "neuanlegen" lassen (durch Adapter neustart), fehlt der Ordner SWITCH mit allen Unterordnern im Ordner STATUS nun komplett.
Dort waren die Datenpunkte hinterlegt, welche die Restlaufzeit, sowie den Progress in Prozent angezeigt haben. Diese Informationen fehlen mir nun komplett. 
Hat Samsung etwas an der API verändert? Oder woran kann das liegen? Habe die DP auch leider an keiner anderen Stelle wiedergefunden.
Ich hoffe es gibt eine Lösung.

Grüße!

Adapter:         0.0.4
JS-Controler:  4.0.23
Node-JS:        16.18.0

**Comment by PastCoder** [comment]
Ich hatte das gleiche Problem (auch Waschmaschine). Dann habe ich entdeckt, dass plötzlich eine Ebene "main." dazwischen ist. Ich habe alle Zugriffe angepasst und seit dem geht es wieder.

**Comment by Hini2001** [comment]
Hey. Vielen Dank. Hab die DP in den tiefen gefunden.  Sonntag gerettet. 😀😉

**Comment by TA2k** [comment]
@PastCoder  könntest du das auch nochmal ins Forum schreiben
https://forum.iobroker.net/topic/48091/test-adapter-samsung-smartthings-v-0-0-x
