### ISSUE TITLE
Datenpunkte bereinigen

### ISSUE THREAD

**Issue by kopierschnitte** [TA2k/ioBroker.smartthings#21]
Es wäre toll, wenn der Adapter Datenpunkte, die Smartthings nicht mehr zurückliefert löschen könnte.

Hintergrund: Mein Kühlschrank macht jede Stunde vier Fotos vom Innenraum und legt dafür etwa acht Datenpunkte pro Foto an. Die alten Datenpunkte laufen dann aber ab und werden eigentlich von der API ab dann auch nicht mehr zurückgegeben.

Im iobroker bleiben sie jedoch und daher musste ich jetzt mal knapp 60T Objekte löschen ;-)

**Comment by TA2k** [comment]
Welchen Pfad hat das genau

**Comment by kopierschnitte** [comment]
Bei mir ist es smartthings.0.ID.status.main.samsungce.viewInside.contents.*

**Comment by TA2k** [comment]
Werden die benötigt sind da die echten Bilder enthalten

**Comment by TA2k** [comment]
Kannst du in den Instanz Optionen noch bei Exclude states
Cycle, viewInside schreiben und manuell die states löschen
