### ISSUE TITLE
Verzögerung vom kompletten IOBroker beim Aktualisieren von Datenpunkten (Waschmaschine)

### ISSUE THREAD

**Issue by Domi920** [TA2k/ioBroker.smartthings#4]
Hallo,
ich habe eine Samsung Waschmaschine in Betrieb mit ewig vielen Datenpunkten.
Immer wenn die Datenpunkte aktualisiert bzw. von Samsung Smartthings angefordert werden bleibt das komplette IOBroker System um 2 -3 Sekunden "hängen".
Dies lässt sich leicht sichtbar machen, wenn man testweise mal im Sekundentakt eine Debug-Meldung im Protokoll schreiben lässt.
Es fällt auf, dass die Meldung nicht sekündlich aktualisiert genau in diesen Zeitpunkt wenn die Datenpunkte abgeholt werden.
Dabei spielt es keine Rolle ob die Datenpunkte in 10, 30 oder 60 Sekundentakt abgeholt werden.

Möglicherweise liegt es daran, weil weit mehr als 100 Datenpunkte abgeholt werden.
Die allermeisten sind nicht zu gebrauchen, weil diese entweder nicht regelmäßig aktualisiert werden, leer sind, oder einfach "Müll" enthalten.
Provisorisch hätte ich schon einige Datenpunkte gelöscht, aber das hatte nichts daran geändert.

So kann ich den Adapter nicht verwenden, weil dieser immer wieder das komplette IOBroker System für kurze Zeit verzögert.
Egal ob man mit einer Fernbedienung ein Licht schaltet, oder die Vis öffnet, ....

Hoffe das dieses Problem beseitigt werden kann, weil es sehr schade um den tollen Adapter wäre.

Vielen Dank im Voraus für die Bemühungen & Arbeit!

**Comment by TA2k** [comment]
Kannst du ein screenshot von den Datenpunkten machen

**Comment by denjo1982** [comment]
leider nicht hab die waschmaschine aus mein konto gelöscht damit ich das problem nicht mehr habe. seid dem läuft alles wieder perfekt

**Comment by Domi920** [comment]
@TA2k ich glaube die viele Anzahl der Datepunkte ist das Problem. Es sind 1234 Datenpunkte nur für die Waschmaschine.
Kann ich die Datenpunkte irgendwie exportieren? Auf einen Screenshot passen diese niemals.


Gruß Dominik

**Comment by TA2k** [comment]
<img width="220" alt="image" src="https://user-images.githubusercontent.com/1307684/194333725-dda3a77a-704e-4429-96d7-0f33306b5605.png">
Aber gut wäre wenn du vorher checkst wo die vielen Elemente genau sind

**Comment by Domi920** [comment]
Die meisten Datenpunkte befinden sich im Verzeichnis:
smartthings.0.9864c106-4053-1a70-24a1-bec0bddbe2a7.status

Allerdings werden manche Datenpunkte falsch, teilweise oder sogar gar nicht beschrieben.

Im Anhang ist der komplette Objektbaum (von Smartthings, aber es gibt sowieso nur die Waschmaschine)


Danke im Voraus für Deine Bemühungen
[smartthings.zip](https://github.com/TA2k/ioBroker.smartthings/files/9727884/smartthings.zip)
!

**Comment by Domi920** [comment]
@TA2k gibt es schon weitere Erkenntnisse oder Lösungsansätze?

Gruß Dominik

**Comment by TA2k** [comment]
So direkt nicht es sind viele Datenpunkte aber eigentlich nichts was ein system überlasten sollte.
Weil die Datenpunkte werden ja nicht erstellt sondern nur der wert gesetzt.

**Comment by Domi920** [comment]
Auch nicht wenns über 1000 bzw. 1234 sind?
Gibt es keine Begrenzung, oder ein Muster, dass nur die brauchbaren Synchronisiert werden?

Wie ist das bei anderen Smartthings Geräten, gibt es auch so ewig viele Datenpunkte?

**Comment by TA2k** [comment]
spontan sehe ich kein Muster sind. Ja ähnlich. Ob es 1000 sind kann ich nicht genau sagen aber viessmann oder lg haben ähnlich viel

**Comment by Domi920** [comment]
Was können wir nun mit den Problemen machen, welches bei vielen Nutzern anscheinend besteht?

Kann man nur gewisse Datenpunkte abholen lassen?
Oder gibt es irgendwo eine Doku welche Datenpunkte von Samsung für z. B. Eine Waschmaschine beschreibtM

**Comment by TA2k** [comment]
nicht das ich wüßte man ruft einfach nur den status von einem gerät ab

**Comment by TA2k** [comment]
welche hardware hat dein system
welche node version 
sind js controller aktuell?

**Comment by Domi920** [comment]
Raspberry Pi 4 Model B 8 GB RAM
Node.js: v16.17.0 
NPM: 8.15.0

**Comment by TA2k** [comment]
Probier mal die GitHub version ob die sich anders verhält

**Comment by Domi920** [comment]
Sieht so aus, als würds gar nicht mehr funktionieren:

`<html>
<body>
<div class="MuiGrid-root MuiGrid-container MuiGrid-item css-n6nfem" style="box-sizing: border-box; display: flex; flex-flow: row wrap; width: 1511.11px; margin: 0px; -webkit-box-align: center; align-items: center; max-width: none; color: rgb(255, 255, 255); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span aria-label="Fehler anzeigen" class="MuiBadge-root BaseBadge-root css-1rzb3uu" style="box-sizing: inherit; position: relative; display: inline-flex; vertical-align: middle; flex-shrink: 0;"><span class="MuiBadge-badge iob1177 iob1178 MuiBadge-standard MuiBadge-anchorOriginTopRight MuiBadge-anchorOriginTopRightRectangular MuiBadge-overlapRectangular MuiBadge-colorError BaseBadge-badge css-1z0bkto" style="box-sizing: border-box; display: flex; flex-flow: row wrap; -webkit-box-pack: center; place-content: center; -webkit-box-align: center; align-items: center; position: absolute; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; font-size: 0.75rem; min-width: 20px; line-height: 1; padding: 0px 6px; height: 20px; border-radius: 10px; z-index: 1; transition: transform 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; background-color: rgb(244, 67, 54); color: rgb(255, 255, 255); top: 10px; right: 10px; transform: scale(1) translate(50%, -50%); transform-origin: 100% 0%;">19</span></span><span aria-label="Fehler und Warnungen anzeigen" class="MuiBadge-root BaseBadge-root css-1rzb3uu" style="box-sizing: inherit; position: relative; display: inline-flex; vertical-align: middle; flex-shrink: 0;"><button class="MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-6ci2yv" tabindex="0" type="button" style="box-sizing: border-box; display: inline-flex; -webkit-box-align: center; align-items: center; -webkit-box-pack: center; justify-content: center; position: relative; -webkit-tap-highlight-color: transparent; background-color: transparent; outline: 0px; border: 0px; margin: 0px; cursor: pointer; user-select: none; vertical-align: middle; appearance: none; text-decoration: none; text-align: center; flex: 0 0 auto; border-radius: 50%; overflow: visible; color: rgb(255, 255, 255); transition: background-color 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; padding: 12px; font-size: 1.75rem;"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="WarningIcon"><path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"></path></svg><span class="MuiTouchRipple-root css-w0pj6f" style="box-sizing: inherit; overflow: hidden; pointer-events: none; position: absolute; z-index: 0; inset: 0px; border-radius: inherit;"></span></button><span class="MuiBadge-badge iob1177 iob1179 MuiBadge-standard MuiBadge-anchorOriginTopRight MuiBadge-anchorOriginTopRightRectangular MuiBadge-overlapRectangular BaseBadge-badge css-1o4n2ye" style="box-sizing: border-box; display: flex; flex-flow: row wrap; -webkit-box-pack: center; place-content: center; -webkit-box-align: center; align-items: center; position: absolute; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; font-size: 0.75rem; min-width: 20px; line-height: 1; padding: 0px 6px; height: 20px; border-radius: 10px; z-index: 1; transition: transform 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; top: 10px; right: 10px; transform: scale(1) translate(50%, -50%); transform-origin: 100% 0%; background-color: rgb(255, 193, 7);">7</span></span><div class="iob1166" style="box-sizing: inherit; flex-grow: 1;"></div><div style="box-sizing: inherit;"><button class="MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium css-1vannuk" tabindex="0" type="button" style="box-sizing: border-box; display: inline-flex; -webkit-box-align: center; align-items: center; -webkit-box-pack: center; justify-content: center; position: relative; -webkit-tap-highlight-color: transparent; outline: 0px; border: 0px; margin: 0px; cursor: pointer; user-select: none; vertical-align: middle; appearance: none; text-decoration: none; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; font-size: 0.875rem; line-height: 1.75; letter-spacing: 0.02857em; text-transform: uppercase; min-width: 64px; padding: 6px 16px; border-radius: 4px; transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, border-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; color: rgba(0, 0, 0, 0.87); background-color: rgb(77, 171, 245); box-shadow: rgba(0, 0, 0, 0.2) 0px 3px 1px -2px, rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;"><span class="MuiButton-startIcon MuiButton-iconSizeMedium css-6xugel" style="box-sizing: inherit; display: inherit; margin-right: 8px; margin-left: -4px;"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="SaveAltIcon"><path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67 2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"></path></svg></span>LOG HERUNTERLADEN<span class="MuiTouchRipple-root css-w0pj6f" style="box-sizing: inherit; overflow: hidden; pointer-events: none; position: absolute; z-index: 0; inset: 0px; border-radius: inherit;"></span></button></div><div class="iob1166" style="box-sizing: inherit; flex-grow: 1;"></div><p class="MuiTypography-root MuiTypography-body2 iob1167 css-68o8xu" title="Geschätzte Größe" style="box-sizing: inherit; margin: 0px 1rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; font-size: 0.875rem; line-height: 1.43; letter-spacing: 0.01071em;">Log-Größe:<span> </span><span class="iob1168" style="box-sizing: inherit; font-style: italic;">863.8 KB</span></p></div><div class="MuiGrid-root MuiGrid-item iob1188 css-1wxaqej" style="box-sizing: border-box; margin: 0px; flex-direction: row; height: 620px; overflow: hidden; max-width: none; color: rgb(255, 255, 255); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiTableContainer-root iob1144 css-kge0eu" style="box-sizing: inherit; width: 1511.11px; overflow-x: auto; height: 620px;">

Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
host.raspberrypi | 2022-10-13 23:59:02.457 | info | instance system.adapter.smartthings.0 started with pid 24164
javascript.0 | 2022-10-13 23:58:42.134 | info | script.js.Überwachung__Systemtests.Protokoll__Error: Überwachung Protokoll, Log:
host.raspberrypi | 2022-10-13 23:58:32.131 | info | Restart adapter system.adapter.smartthings.0 because enabled
host.raspberrypi | 2022-10-13 23:58:32.131 | error | instance system.adapter.smartthings.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi | 2022-10-13 23:58:28.911 | info | instance system.adapter.smartthings.0 started with pid 23841
host.raspberrypi | 2022-10-13 23:58:28.305 | info | "system.adapter.smartthings.0" enabled
host.raspberrypi | 2022-10-13 23:58:22.361 | info | "system.adapter.smartthings.0" disabled
javascript.0 | 2022-10-13 23:58:17.903 | info | script.js.Überwachung__Systemtests.Protokoll__Warn: Überwachung Protokoll, Log:
javascript.0 | 2022-10-13 23:58:17.900 | info | script.js.Überwachung__Systemtests.Protokoll__Error: Überwachung Protokoll, Log:
host.raspberrypi | 2022-10-13 23:58:07.894 | warn | Do not restart adapter system.adapter.smartthings.0 because restart loop detected
host.raspberrypi | 2022-10-13 23:58:07.893 | info | Restart adapter system.adapter.smartthings.0 because enabled
host.raspberrypi | 2022-10-13 23:58:07.893 | error | instance system.adapter.smartthings.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
smartthings.0 | 2022-10-13 23:58:07.184 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
smartthings.0 | 2022-10-13 23:58:06.680 | error | this.subscribeStates is not a function
smartthings.0 | 2022-10-13 23:58:06.678 | error | TypeError: this.subscribeStates is not a function at new Smartthings (/opt/iobroker/node_modules/iobroker.smartthings/main.js:33:10) at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.smartthings/main.js:354:3) at Module._compile (node:internal/modules/cjs/loader:1126:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) at Module.load (node:internal/modules/cjs/loader:1004:32) at Function.Module._load (node:internal/modules/cjs/loader:839:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) at node:internal/main/run_main_module:17:47
smartthings.0 | 2022-10-13 23:58:06.675 | error | uncaught exception: this.subscribeStates is not a function
host.raspberrypi | 2022-10-13 23:58:04.723 | info | instance system.adapter.smartthings.0 started with pid 23457
host.raspberrypi | 2022-10-13 23:58:03.851 | info | "system.adapter.smartthings.0" enabled

</div></div>
</body>
</html>`

**Comment by TA2k** [comment]
sorry nochmal installieren

**Comment by Domi920** [comment]
Funktioniert wieder.
Leider ändert sich nichts am Einfrieren vom IOBroker :-(

**Comment by TA2k** [comment]
Nochmal installieren und schauen ob sich was ändert

**Comment by TA2k** [comment]
Ich habe noch was geändert und schauen ob es immer noch so ist
Ich habe die schreibende Vorgänge auf sequenziell anstatt alle parallel und eine pause zwischen den schreibvorgänge
Ich habe jetzt die Pause mal entfernt und bitte testen ob es immer noch geht

**Comment by Domi920** [comment]
Klappt immer noch :-)

**Comment by denjo82** [comment]
Läuft jetzt??

**Comment by Domi920** [comment]
@denjo82 ja, bei der v0.4 aus Gibthub klappts einwandfrei.
Denke dass es demnächst offiziell zum Downloaden über IOBroker Adapter geht.

Gruß Dominik :-)
